[build]
  publish = ".next"
  command = "npm run build"

[[redirects]]
  from = "https://portfoliorayhan.netlify.app/*"
  to = "https://www.portfoliorayhan.netlify.app/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
[[plugins]]
  package = "@netlify/plugin-nextjs"
